import { Validators } from "@angular/forms";

export const FIRST_STEP_FORM = {
  codfilial: [""],
  numped: [""],
  numnota: [""],
  nomeVendedorOrcamento: [""],
  fase: [""],
  status: [""],
  statusseparacao: [""],
  tpvenda: [""],
  statusautorizacao: [""],
  numorca: [""],
  numorcfilial: [""],
  percdif: [""],
  dtvalidasefaz: [""],
  dtorca: [""],
  dtorc: [""],
  orcadopor: [""],
  bairro: [""],
  cidade: [""],
  codigo: [""],
  valorSaldo: [""],
  uf: [""],
  cep: [""],
  fone: [""],
  ie: [""],
  cnpj: [""],
  cliente: [""],
  email: [""],
  codplpag: ["", [Validators.required]],
  codplpag2: ["", [Validators.required]],
  condicaoorc: [""],
  codcob: [null, [Validators.required]],
  limcred: [""],
  bloqueio: [""],
  dtbloq: [""],
  codusur1: ["", [Validators.required]],
  nomeusur1: [""],
  codusur2: [""],
  nomeusur2: [""],
  codtransportadora: [""],
  dtabertcc1: [""],
  dtabertcc2: [""],
  endereco: [""],
  codpraca: [""],
  emailnfe: [""],
  emailalternativo: [""],
  celularalternativo: [""],
  regiao: [""],
  seqrepresentante: [""],
  representante: [""],
  obsgeral: [""],
  vlrreceber: [""],
  vlrseparado: [""],
  vlrdisponivel: [""],
  vlrvencido: [""],
  vlravencer: [""],
  usuario: [""],
  codcliprinc: [""],
  codcli: [""],
  fantasia: [""],
  clientesvinculados: [""],
  filiaiscliente: [""],
  whatsapp: [""],
  nomeWhatsapp: [""],
  codfilialorigorc: [""],
  tpretirada: ["", [Validators.required]],
  modfrete: ["", [Validators.required]],
  tporc: ["V", [Validators.required]],
  tpvencto: [0, [Validators.required]],
  transportadora: [{ value: "", disabled: true }],
  contribuinte: [""],
  consumidorfinal: [""],
  calculast: [""],
  clientefontest: [""],
  partilha: [""],
  dtultatucad: [""],
  bloqueiosefaz: [""],
  matricula: [""],
  codusur: [""],
  codfornec: [""],
  hasTransportadora: [null, [Validators.required]],
  hasCliente: [null, [Validators.required]],
};

export const SECOND_STEP_FORM = {
  numorca: [""],
  dtorca: [""],
  codusur1: [""],
  codfilial: [""],
  numorcfilial: [""],
  codigo: [""],
  cliente: [""],
  cnpj: [""],
  ie: [""],
  ufdestino: [""],
  codepto: [""],
  codprod: [""],
  descricao: [""],
  descricaoDepto: [""],
  codfab: [""],
  embalagem: [""],
  codprodcli: [""],
  selestoque: ["0"],
  numregiao: [""],
  percdesc: [""],
  numseq: [""],
};

export const THIRD_STEP_FORM = {
  codfilial: [""],
  numorcfilial: [""],
  tpvenda: [""],
  numorcfilialcompl: [""],
  numpedcli: [""],
  regiao: [""],
  numnota: [""],
  fase: [""],
  situacao: [""],
  statusautorizacao: [""],
  status: [""],
  numped: [""],
  dtorca: [""],
  numorca: [""],
  codigo: [""],
  cliente: [""],
  cnpj: [""],
  ie: [""],
  nomecontato: [""],
  obs1cab: [""],
  obs2: [""],
  ufdestino: [""],
  endereco: [""],
  numero: [""],
  complemento: [""],
  bairro: [""],
  cidade: [""],
  uf: [""],
  cep: [""],
  contato: [""],
  enderecoentrega: [""],
  numeroentrega: [""],
  complementoentrega: [""],
  bairroentrega: [""],
  cidadeentrega: [""],
  ufentrega: [""],
  cepentrega: [""],
  contatoentrega: [""],
  qtdevolumes: [""],
  especievolumes: [""],
  marca: [""],
  pesobruto: [""],
  pesoliquido: [""],
  vlrfrete: [null],
  observacao: [""],
  obsorc: [""],
  obsentrega1: [""],
  obsentrega2: [""],
  obsprevisaosaida: [
    {
      value: "",
      disabled: true,
    },
  ],
  obsavulsa: [
    {
      value: "",
      disabled: true,
    },
  ],
};
